### ISSUE TITLE
angular-highcharts contains deep imports

### ISSUE THREAD

**Issue by OysteinAmundsen** [cebor/angular-highcharts#360] opened 2021-02-09 10:24 UTC
I get the following warning in angular build:

> Entry point 'angular-highcharts' contains deep imports into '~/node_modules/highcharts/highmaps', '~/node_modules/highcharts/highstock'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

Upon source-map-explorer inspection, I find that the tree-shaker could not remove neither highmaps nor highstock, even though I am not using that functionality in my app. By removing these deep imports, I could drastically decrease my bundle size. 

I know that Highcharts is almost ESM compatible (https://github.com/highcharts/highcharts/issues/12738), so these deep imports may no longer be necessary?

**Comment by cebor** [comment] 2021-02-09 14:50
I tried to fix this several times, but if i use anything other than a global import for highmaps or highstocks, the lib stops working.

The only way to import highmaps or highstock to my lib is the following:

`import * as Highcharts from 'highcharts/highmaps';`

**Comment by cebor** [comment] 2021-02-09 14:53
If you have some ideas to fix this, i would be happy about a pull request.

Affected files are here:
https://github.com/cebor/angular-highcharts/blob/5cb5b3fb6ec399e5ffd4b70041f80248a4db6ad1/projects/angular-highcharts/src/lib/mapchart.ts#L3
https://github.com/cebor/angular-highcharts/blob/5cb5b3fb6ec399e5ffd4b70041f80248a4db6ad1/projects/angular-highcharts/src/lib/stockchart.ts#L3

and

https://github.com/cebor/angular-highcharts/blob/5cb5b3fb6ec399e5ffd4b70041f80248a4db6ad1/projects/angular-highcharts/src/public-api.ts#L9

**Comment by cebor** [comment] 2021-02-09 14:56
Its also a dupe of #325

**Closed by cebor** 2021-02-09 14:56 UTC
Labels: help wanted
