### ISSUE TITLE
webgl / boost-canvas

### ISSUE THREAD

**Issue by bonaparte89** [cebor/angular-highcharts#45] opened 2017-06-19 07:53 UTC
hello,

since updating to the latest highcharts and angular-highcharts i'm running into this highcharts 27 error... you need to include boost-canvas and boost .js... I added those but the error still appears. Did anyone manage this?

using systemjs.

https://www.highcharts.com/errors/27 

regards

**Comment by cebor** [comment] 2017-06-19 09:08
Hi, since v3 we don't ship a umd bundle, which is a requirement for systemjs.

But i think i will re add the umd bundle and support systemjs again.

**Comment by cebor** [comment] 2017-06-19 09:26
@bonaparte89 landed in v3.3.0, can you test if it works?

**Comment by bonaparte89** [comment] 2017-06-19 09:57
thanks that was quick! 
but still the highcharts 27 error shows up :(

**Comment by cebor** [comment] 2017-06-19 14:17
Can you build me a Plunker like this: https://plnkr.co/edit/yrPSBbGftdTI8N4lASyG?p=preview to reproduce the issue.

**Comment by cebor** [comment] 2017-06-21 08:39
@bonaparte89 

Have you tried to import the missing modules, like described here: https://github.com/cebor/angular-highcharts#using-highcharts-modules

**Comment by bonaparte89** [comment] 2017-06-21 08:43
I mapped them and tried to import them just like that. no success. The error appears when I initialize the application... So added the boost-stuff to my entry component.. nothing.... I haven't yet tried to just add them within your module. Might try this later. but this shouldn't actually change a thing...

**Comment by attilacsanyi** [comment] 2017-07-27 14:50
`boost-canvas` then `boost` module, order matters @bonaparte89. Did you include in this order?

**Comment by bonaparte89** [comment] 2017-07-27 15:03
yes did so.

**Closed** 2017-10-17 09:52 UTC
