### ISSUE TITLE
how to use callback function for tooltop.formatter?

### ISSUE THREAD

**Issue by Yooke** [cebor/angular-highcharts#9] opened 2016-09-27 03:33 UTC
At javascript:

```javascript
tooltip: {
    formatter: function () {
        return new Date(this.x).toLocaleString() + '<br><b>内存：</b>' + byte_to_string(this.y)
    }
}
```

But typescript this is a class.

**Comment by cebor** [comment] 2016-09-27 09:52
The options object gets extracted from the Charts object, so it should work as you described.

Docs: http://www.highcharts.com/docs/chart-concepts/tooltip

**Comment by Yooke** [comment] 2016-09-28 02:38
@cebor thanks 
`byte_to_string` is a function convert Byte to KB  MB or GB,  like this:
`private byteToString(data: any): string {
        let kb = data / 1024
        if (kb > 1024) {
            let mb = kb / 1024
            if (mb > 1024) {
                return (mb / 1024).toFixed(2) + ' GB'
            } else {
                return mb.toFixed(2) + ' MB'
            }
        }
        return kb.toFixed(2) + ' KB'
    }`
now browser console print:  _Uncaught TypeError: this.byteToString is not a function_

**Comment by cebor** [comment] 2016-09-28 08:12
I think the Problem is that, the options object and the class where you creating the Chart have different contexts. 

Maybe making `byteToString` to a static method will solve this.

For further help, please show me more code of the class you declaring your chart.

**Comment by cebor** [comment] 2016-09-30 07:48
I think, the problem is solved, so i'm closing this. Feel free to reopen.

**Closed by cebor** 2016-09-30 07:48 UTC
Labels: question

**Comment by Yooke** [comment] 2016-10-09 06:50
yes, is solved. thanks.
