### ISSUE TITLE
Can't bind to 'chart' since it isn't a known property of 'div'. 

### ISSUE THREAD

**Issue by dice2019** [cebor/angular-highcharts#90] opened 2017-11-06 05:42 UTC
use demo in html:
`<div [chart]="chart"></div>`

```
use version:
    "@angular/core": "4.3.2",
    "angular-highcharts": "4",
    "@types/highcharts": "^5.0.10",
    "highcharts": "^6.0.2",
```

**Comment by cebor** [comment] 2017-11-06 10:33
Can you show your app.module.ts ?

**Comment by superestze** [comment] 2017-11-07 05:37
- youvshould import the chartModel into app.module.ts or current index.ts

**Comment by cebor** [comment] 2017-11-08 09:49
Closing this, feel free to reopen!

**Closed by cebor** 2017-11-08 09:49 UTC

**Comment by th0g0th** [comment] 2017-11-11 16:03
@cebor I got a same issues. But I can't find any chartModel here? Can you show me?

**Comment by cebor** [comment] 2017-11-11 18:37
@th0g0th please post you app.module.ts

**Comment by th0g0th** [comment] 2017-11-12 17:57
I'm using [angular-seed](https://github.com/mgechev/angular-seed). 

**app.module.ts**
````javascript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

import { AboutModule } from './about/about.module';
import { HomeModule } from './home/home.module';
import { SharedModule } from './shared/shared.module';
import { ChartModule } from 'angular-highcharts';

@NgModule({
  imports: [BrowserModule, HttpModule, AppRoutingModule, AboutModule, HomeModule, ChartModule, SharedModule.forRoot()],
  declarations: [AppComponent],
  providers: [{
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  }],
  bootstrap: [AppComponent]

})
export class AppModule { }

````

**system.config.js**
````javascript
    packages: {
      highcharts: {
        main: './highcharts.js',
        defaultExtension: 'js'
      },
      'angular-highcharts': {
        main: './angular-highcharts.js',
        defaultExtension: 'js'
      }
    }
````

**Comment by cebor** [comment] 2017-11-12 20:33
Appmodule seems to be configured correct.

Maybe you have to import it also in the submodule where you using it within.

**Comment by cebor** [comment] 2017-11-12 21:53
@th0g0th in case you using systemjs, please try to use `./angular-highcharts.umd.js`

**Comment by th0g0th** [comment] 2017-11-13 15:38
@cedor It’s not working.

**Comment by cebor** [comment] 2017-11-13 18:55
@th0g0th if you create a repo where this issue is reproducible i can take look at it.

**Comment by nirali-ga** [comment] 2018-03-06 14:14
Hello,
     In your angular App if you have submodules and inside that module's component file if you are trying to implement any chart , you will get above error, but if you  import  same things and other code as you do in app.module.ts  as mentioned in API doc and usage then your problem will get solved.I dont know this is ideal solution or not but I have done this and removed this code from main app.module.ts.

Hope this helps someone.
