### ISSUE TITLE
Highcharts More issue with Angular 5 dev mode...

### ISSUE THREAD

**Issue by shermax** [cebor/angular-highcharts#117] opened 2018-01-09 12:46 UTC
Hi!

I am facing issue with Angular 5 dev build (ng serve). 
It is happening if I add highcharts more module from 'highcharts/highcharts-more.src'

There is an error:

TypeError: chartModule is not a function
    at eval (angular-highcharts.es5.js:245)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (angular-highcharts.es5.js:244)
    at new ChartModule (angular-highcharts.es5.js:274)
    at _createClass (core.js:10915)
    at _createProviderInstance$1 (core.js:10889)
    at initNgModule (core.js:10842)
    at new NgModuleRef_ (core.js:12096)
    at createNgModuleRef (core.js:12086)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14430)

If I build for production (ng serve --prod) all is ok. But not working with dev (ng serve) build...

-----------------------------------------------------------------------------------------------
**There are my configuration files:**
-----------------------------------------------------------------------------------------------

**package.json**

{
  "name": "altanga",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular-highcharts": "^5.2.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "highcharts": "^6.0.4",
    "jquery": "^3.2.1",
    "rxjs": "^5.5.2",
    "slick-carousel": "^1.8.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/highcharts": "^5.0.15",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

-----------------------------------------------------------------------------------------------
**.angular-cli.json**

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "altanga"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/slick-carousel/slick/slick.css",
        "../node_modules/slick-carousel/slick/slick-theme.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js",
        "../node_modules/slick-carousel/slick/slick.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

-----------------------------------------------------------------------------------------------
**app.module.ts**

import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';

import {AppComponent} from './app.component';

import {ChartModule, HIGHCHARTS_MODULES} from 'angular-highcharts';
import {HeaderComponent} from './components/header/header.component';
import {FooterComponent} from './components/footer/footer.component';
import {HomeComponent} from './components/home/home.component';
import {SlickModule} from './shared/slick';

import more from 'highcharts/highcharts-more.src';

export function highChartsModules() {
  return [more];
}

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    FooterComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule,
    ChartModule,
    SlickModule.forRoot()
  ],
  providers: [
    {provide: HIGHCHARTS_MODULES, useFactory: highChartsModules}
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}

Thanks!

**Comment by cebor** [comment] 2018-01-09 12:52
Duplicate of: https://github.com/cebor/angular-highcharts/issues/112

**Closed by cebor** 2018-01-09 12:52 UTC
